<!DOCTYPE HTML>

<html>
<head>

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Your Website</title>

	<?php
		include('./header.phtml');
	
	?>

	<div class="container" >
	<div class="span12">
	<table class="table" >
		<tr>
			<td colspan="6" >
				<div class="span6 cadre">
				<img src="./images/other/DSC06503.JPG"  />
				</div>
			</td>
			<td colspan="5" class="text-center vert-center">
			<div class="text-center">
				<?= $translator->gettext('description1'); ?>
				</div>
				
			</td>
		</tr>
	<tr>
		<td colspan="5" class="vert-center">
			<div class="text-center">
				<?= $translator->gettext('description2'); ?>
				</div>
		</td>
			<td colspan="6">
				<div class="span6 cadre">
				<img src="./images/other/DSC06476.JPG"  />
				</div>
		</td>
	</tr>
</table>
</div>
</body>

</html>