<!DOCTYPE HTML>

<html>
<head>

	

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Your Website</title>

	<?php
		include('./header.phtml');
	
	?>

	<div class="container" >
	<table class="table" >
		<tr>
			
		
			<td class="text-center vert-center" >
				<div class="span6" >
				<img src="./images/other/DSC06503.JPG"  />
			</div>
				
				<div class="span5 text-center vert-center" >
				<?= $translator->gettext('description1'); ?>
				</div>
			</td>
		</tr>
	<tr>
		<td class="" >
		<div class="span5 text-center vert-center" >
				<?= $translator->gettext('description2'); ?>
				</div>
		
		<div class="span6">
		
				<img src="./images/other/DSC06476.JPG"  />
			</div>
		</td>
	</tr>
</table>
</body>

</html>