<!DOCTYPE HTML>

<html>
<head>

	

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Your Website</title>

	<?php
		include('./header.phtml');
	
	?>

	
	<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDivJXpAtTrE7E_niBoCqZQAPrfuxUB4Yo&sensor=false">
    </script>
    <script type="text/javascript">
		var map;
		var position;

		
		function codeAddress(address) {
			//set position
			var position = new google.maps.LatLng(47.18942, -1.54521);
			
			var mapOptions = {
				  center: position,
				  zoom: 8,
				  mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
			  
			  var marker = new google.maps.Marker({
				  map: map,
				  position: position
			  });
			  var infowindow = new google.maps.InfoWindow();
			  
			  var text = '<b>BRETON Gille</b><br/>'+address;
				text = text+'</br><a href="https://maps.google.com/maps?saddr=&daddr=' + address + '" target="_blank"><span class="icon-road" ></span><?= $translator->gettext('itineraire'); ?></a>';
			   
			  
				infowindow.setContent(text);
			  //create listener for marker infowindow and set content
			google.maps.event.addListener(marker, 'click', function() { 
				infowindow.close();
				
				infowindow.open(map,marker);
			});
			
			
				/***** GET Localisation *******/
				
				
	  
				
				// if(navigator.geolocation){
					// navigator.geolocation.getCurrentPosition(function (position) {  
						
					// This gets the
						// var latitude = position.coords.latitude;                    //users current
						// var longitude = position.coords.longitude;                 //location
						// var coords = new google.maps.LatLng(latitude, longitude); //Creates variable for map coordinates
						
						// alert(latitude+':'+longitude);
					// },function (position) {  
					
				// }
			  /********************************************/
			// } else {
			  // alert('Geocode was not successful for the following reason: ' + status);
			// }
		  // });
		}


	
	
	
      function initialize() {

		var addr = "22 Rue Joseph Turbel, 44400 Rez&eacute;";
		 codeAddress(addr);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

	<div class="container" >
		<div id="map-canvas" class="Gmap" />
	</div>

</body>

</html>