<!DOCTYPE HTML>

<html>
<head>

	

	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title>Your Website</title>

	<?php
		include('./header.phtml');
	
	?>

	
	<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDivJXpAtTrE7E_niBoCqZQAPrfuxUB4Yo&sensor=false">
    </script>
    <script type="text/javascript">
		var geocoder;
		var map;
		var position;

		
	  function withoutLocalisation(err){
		alert("ok");
	  }
		function codeAddress(address) {
		  geocoder.geocode( { 'address': address}, function(results, status) {
			if (status == google.maps.GeocoderStatus.OK) {
			  /*map.setCenter(results[0].geometry.location);
			  var marker = new google.maps.Marker({
				  map: map,
				  position: results[0].geometry.location
			  });*/
			  position = results[0].geometry.location;
			  
			var mapOptions = {
				  center: position,
				  zoom: 8,
				  mapTypeId: google.maps.MapTypeId.ROADMAP
			};
			map = new google.maps.Map(document.getElementById("map-canvas"),
            mapOptions);
			  
			  var marker = new google.maps.Marker({
				  map: map,
				  position: results[0].geometry.location
			  });
			  var infowindow = new google.maps.InfoWindow();
			  
			  var text = '<b>LE CAN Maxime</b><br/>'+address;
				text = text+'</br><a href="https://maps.google.com/maps?saddr=&daddr=' + address + '" target="_blank"><span class="icon-road" ></span><?= $translator->gettext('itineraire'); ?></a>';
			   
			  
				infowindow.setContent(text);
			  //create listener for marker infowindow and set content
			google.maps.event.addListener(marker, 'click', function() { 
				infowindow.close();
				
				infowindow.open(map,marker);
			});
			
			
				/***** GET Localisation *******/
				
				
	  
				
				// if(navigator.geolocation){
					// navigator.geolocation.getCurrentPosition(function (position) {  
						// alert("ok");
					// This gets the
						// var latitude = position.coords.latitude;                    //users current
						// var longitude = position.coords.longitude;                 //location
						// var coords = new google.maps.LatLng(latitude, longitude); //Creates variable for map coordinates
						
						// alert(latitude+':'+longitude);
					// },function (position) {  
						// alert("ok");});
				// }
			  /********************************************/
			} else {
			  alert('Geocode was not successful for the following reason: ' + status);
			}
		  });
		}


	
	
	
      function initialize() {
		geocoder = new google.maps.Geocoder();

		var addr = "8 boulevard petit port, 44300 NANTES FRANCE";
		 codeAddress(addr);
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>

	<div class="container" >
		<div id="map-canvas" class="Gmap" />
	</div>

</body>

</html>